apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: my-app-cronjob
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: my-app-container
            image: my-app-image:latest
            command: ["cron-job-script.sh"]

