apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
  - name: main-container
    image: main-app-image:latest
  - name: sidecar-container
    image: sidecar-app-image:latest

