apiVersion: batch/v1
kind: Job
metadata:
  name: my-app-job
spec:
  template:
    spec:
      containers:
      - name: my-app-container
        image: my-app-image:latest
        command: ["job-script.sh"]

