apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: secret-container
    image: secret-app-image:latest
    env:
    - name: SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: secret-key

